spring:
  application:
    name: nexty
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nexty
    username: nexty
    password: nexty123
jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      show_sql: true
      format_sql: true

liquibase:
change-log: classpath:db/changelog/master.xml

server:
  port: 8080
  servlet:
    context-path: /api
jwt:
  secret: password
